### ISSUE TITLE
Hi, can you release the code of visualization of image matching results?

### ISSUE THREAD

**Issue by GNN-zl** [Thinklab-SJTU/ThinkMatch#17]
I'm very interested in how the matching result can be displayed on the image.
Thanks.

**Comment by suze521** [comment]
me too

**Comment by rogerwwww** [comment]
Hi guys,

We do have a visualization code but it was poorly written and not ready for release, and unfortunately we are now working on a tight schedule to some paper deadlines. I will consider working on it shortly after I am available and sorry for the inconvenience.

**Comment by yuzhenglin** [comment]
Thanks

**Comment by LiangGaoUser** [comment]
@rogerwwww 
Hi guys , have you released the visualization code in current project?

**Comment by xiachenrui** [comment]
I'm also looking forward to the release of the visualization code！

**Comment by rogerwwww** [comment]
For anyone who is still looking for the visualization code: please check out [the example gallery](https://pygmtools.readthedocs.io/en/latest/auto_examples/index.html) in our new project ``pygmtools``! Also, please [star it](https://github.com/Thinklab-SJTU/pygmtools/stargazers) if you like it 🤗🤗

**Comment by rogerwwww** [comment]
I am closing this non-active issue. Feel free to reopen it if you still have any questions.
