### ISSUE TITLE
File lost for synthetic data

### ISSUE THREAD

**Issue by awp4211** [Thinklab-SJTU/ThinkMatch#25]
Hi,
Could you upload the synthetic.py located in src/dataset?

Thanks

**Comment by rogerwwww** [comment]
Hi there,

Our previous implementation of synthetic data is of low quality, and we are reorganizing the code. It will be published once it is ready. Sorry for the inconvenience.

**Comment by rogerwwww** [comment]
This issue shall be resolved by the commit: https://github.com/Thinklab-SJTU/ThinkMatch/commit/a60d228bca0410a69108988578805d641f2c0a3a. If you have any questions, feel free to reopen it!
