### ISSUE TITLE
ModuleNotFoundError: No module named 'lpmp_py'

### ISSUE THREAD

**Issue by xiabc612** [Thinklab-SJTU/ThinkMatch#26]
Hello, when I run the code with python train_eval.py --cfg experiments/vgg16_bbgm_voc.yaml, an error occurred.
Traceback (most recent call last):
  File "ThinkMatch-master/models/BBGM/model.py", line 6, in <module>
    from lpmp_py import GraphMatchingModule
ModuleNotFoundError: No module named 'lpmp_py'

**Comment by rogerwwww** [comment]
Hi there, have you successfully installed LPMP by ``python -m pip install git+https://git@github.com/rogerwwww/lpmp.git``?

**Comment by xiabc612** [comment]
Thanks for your reply and the problem have been solved.
