### ISSUE TITLE
Sinkhorn algorithm

### ISSUE THREAD

**Issue by nurlanov-zh** [Thinklab-SJTU/ThinkMatch#27]
Thank you for such a nice library!

I have a question regarding Sinkhorn iterations: how much does the convergence of the whole pipeline depend on temperature parameter (`tau`)? I know that there is a tradeoff between binariness of ds matrix and stability of gradients. I am wondering how much grid search of this parameter is required? Does it also depend on implementation: `forward_log` and `forward_ori`?

**Comment by rogerwwww** [comment]
Hi there, 

Thank you for your interest!

According to my own experience, `tau` needs to be carefully tuned. `forward_log` also provides a more stable gradient, and using it is beneficial to the convergence of the whole pipeline.
