### ISSUE TITLE
How to get the keypoints for a general dataset?

### ISSUE THREAD

**Issue by Tramac** [Thinklab-SJTU/ThinkMatch#28]
@rogerwwww Hi Runzhong, thanks for your excellent work！There are some doubts: how to get the keypoints of the image for a general datasets? 
Looking forward to your reply！

**Comment by rogerwwww** [comment]
Hi there,

There are many keypoint detectors available for initializing the keypoints, for example the SIFT detector as a classic keypoint detector.

Besides, you might be interested in recent keypoint detection methods based on deep learning (for example, human pose estimation methods).

**Comment by Tramac** [comment]
Thanks for your reply! 
If using the classic detector, how to obtain the correspondence between the keypoints of the two graphs (or how to get the label)? And will the quality of keypoints affect the result of graph matching?

**Comment by rogerwwww** [comment]
Just my personal suggestion: you may adopt a pre-trained graph matching model (or perhaps a learning-free graph matching algorithm) to compute the initial matching, and then manually fix the wrong matching.

If you find the deep graph matching method performs poorly on a new dataset, you may change the CNN feature extractor according to your own use cases. The back-end graph matching modules in this repo should be generalizable to various cases.
