### ISSUE TITLE
Difference between eval.py and eval_qap.py

### ISSUE THREAD

**Issue by xmlyqing00** [Thinklab-SJTU/ThinkMatch#39]
Hi,

Thanks for providing a comprehensive benchmark. I have a question about the differences between `eval.py` and `eval_qap.py`, and `train_eval.py` and `train_eval_qap.py`.

Thanks

**Comment by rogerwwww** [comment]
Hi Yongqing,

If you want to run the image matching task, run ``train_eval.py`` and ``eval.py``. If you want to study the QAPLIB instances, run ``train_eval_qap.py`` and ``eval_qap.py``.

**Comment by xmlyqing00** [comment]
I see. Thank you!!

Just want to make sure, does `image matching task` refer to Psacal VOC and Willow?

**Comment by rogerwwww** [comment]
> Just want to make sure, does `image matching task` refer to Psacal VOC and Willow?

Yes

**Comment by xmlyqing00** [comment]
Thank you
