### ISSUE TITLE
Error when running python train_eval.py --cfg experiments/vgg16_pca_voc.yaml

### ISSUE THREAD

**Issue by tztgogo** [Thinklab-SJTU/ThinkMatch#40]
![05d3b31103d32b1fe1fd11b903c4365](https://user-images.githubusercontent.com/54180691/155047723-0696b965-eb98-43d6-8c19-d876f1494a39.png)

And at the end of the bug report it showes:

![image](https://user-images.githubusercontent.com/54180691/155047819-2e600de3-359f-4c14-8533-297bd771293c.png)

Can you help me with this

**Comment by rogerwwww** [comment]
As suggested by the warning message, have you tried installing and using the g++ compiler?

Besides, to compile the extension code correctly, could you please check:
* Your GCC version is between 4.8 and 6
* A suitable version of CUDA is correctly installed and configured, including the nvcc compiler

**Comment by tztgogo** [comment]
> As suggested by the warning message, have you tried installing and using the g++ compiler?
> 
> Besides, to compile the extension code correctly, could you please check:
> 
> * Your GCC version is between 4.8 and 6
> * A suitable version of CUDA is correctly installed and configured, including the nvcc compiler

I have downgraded my gcc version to 7.2 as the Readme instructed,and the cudatoolkit is 10.1 as instructed.however the ninja still can not be built.
![image](https://user-images.githubusercontent.com/54180691/155127035-56aa0fda-9373-446d-94b7-892d3a6ad796.png)

**Comment by rogerwwww** [comment]
I am glad to hear that you have resolved this issue! BTW your screenshot suggests that ``nvcc`` is not found.
