### ISSUE TITLE
GANN results on CUB dataset

### ISSUE THREAD

**Issue by nurlanov-zh** [Thinklab-SJTU/ThinkMatch#43]
Hello,

There are results published in GANN-MGM paper on CUB dataset. However, the f1-scores are given as a plot. I am wondering if there are numbers corresponding to those plots? Intra-, cross- class variations as in CIE-H paper? Accuracies with intersection filtering?
Thanks.

Best,
Zhak

**Comment by rogerwwww** [comment]
Hi Zhak,

Here are the numbers in the plots:

On training data:

model  | precision | var | recall | var | f1 | var
 -- | -- | -- | -- | -- | -- | --
 GANN-2GM | 0.499496 | 0.301 | 0.700436 | 0.262 | 0.533372 | 0.305
 GANN-MGM | 0.589244 | 0.290 | 0.748422 | 0.251 | 0.626582 | 0.288

On testing data:

model  | precision | var | recall | var | f1 | var
 -- | -- | -- | -- | -- | -- | --
 GANN-2GM | 0.621188 | 0.280 | 0.692986 | 0.210 | 0.652978 | 0.21
GANN-MGM | 0.655786 | 0.250 | 0.710145 | 0.170 | 0.679424 | 0.150

I do not have the other results you required at hand, and you may adjust the config file and run it on your own. I wish these will be helpful.

**Comment by nurlanov-zh** [comment]
Thanks! It is helpful!
