### ISSUE TITLE
Whether it can run on CPU

### ISSUE THREAD

**Issue by zyiyid** [Thinklab-SJTU/ThinkMatch#45]
I tried to run the project on the CPU, but it failed to compile cpp_extension.

**Comment by rogerwwww** [comment]
Hi there, 

Since you are using CPU, you may not need the cpp_extension code. Perhaps you should manually comment out related imports like:

https://github.com/Thinklab-SJTU/ThinkMatch/blob/master/src/sparse_torch/csx_matrix.py#L7-L16

to stop the automatic compiling of cpp_extension code.

**Comment by zyiyid** [comment]
Yes, I've done that and now it works.  Thank you for your answer.
