### ISSUE TITLE
Error when running  python  train.py 

### ISSUE THREAD

**Issue by chengzhix** [Thinklab-SJTU/ThinkMatch#46]
Hi, when I run the code, there exists a problem, it can't find the sparse_dot module.

> (graph) crypto@crypto-Inspiron-3881:~/think$ python train_eval.py --cfg experiments/vgg16_pca_voc.yaml
> Using /home/crypto/.cache/torch_extensions as PyTorch extensions root...
> Detected CUDA files, patching ldflags
> Emitting ninja build file /home/crypto/.cache/torch_extensions/sparse_dot/build.ninja...
> Building extension module sparse_dot...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> 1.7.2
> Loading extension module sparse_dot...
> Traceback (most recent call last):
>   File "train_eval.py", line 8, in <module>
>     from src.dataset.data_loader import GMDataset, get_dataloader
>   File "/home/crypto/think/src/dataset/data_loader.py", line 9, in <module>
>     from src.factorize_graph_matching import kronecker_sparse, kronecker_torch
>   File "/home/crypto/think/src/factorize_graph_matching.py", line 4, in <module>
>     from src.utils.sparse import bilinear_diag_torch
>   File "/home/crypto/think/src/utils/sparse.py", line 8, in <module>
>     from src.sparse_torch import CSRMatrix3d, CSCMatrix3d
>   File "/home/crypto/think/src/sparse_torch/__init__.py", line 5, in <module>
>     from .csx_matrix import CSRMatrix3d, CSCMatrix3d, dot, concatenate
>   File "/home/crypto/think/src/sparse_torch/csx_matrix.py", line 16, in <module>
>     verbose=True
>   File "/home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 974, in load
>     keep_intermediates=keep_intermediates)
>   File "/home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1192, in _jit_compile
>     return _import_module_from_library(name, build_directory, is_python_module)
>   File "/home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1536, in _import_module_from_library
>     file, path, description = imp.find_module(module_name, [path])
>   File "/home/crypto/anaconda3/envs/graph/lib/python3.7/imp.py", line 296, in find_module
>     raise ImportError(_ERR_MSG.format(name), name=name)
> ImportError: No module named 'sparse_dot'

**Comment by rogerwwww** [comment]
Hi, I did not encounter this issue before. Could you provide more information so that we can reproduce this issue? For example, your system version, your python package version, and your ThinkMatch version.

**Comment by chengzhix** [comment]
When I started to run the code, firstly I got an error like below,I found some way to change ['ninja', '-v'] to ['ninja', '--version'], then the first [error](https://github.com/Thinklab-SJTU/ThinkMatch/issues/46#issue-1190620692) appears , I guess this solution is incorrect. I think I have the same error with [issue#40](https://github.com/Thinklab-SJTU/ThinkMatch/issues/40#issue-1146363244).

> ubuntu:16.04
> ThinkMatch version: 0.1.0
> lpmp-py                    0.0.1                    
> ninja                         1.9.0            
> python                      3.7.7                
> python-dateutil         2.8.2                    
> python-louvain         0.16                   
> pytorch                    1.6.0           
> torch-cluster            1.5.8                    
> torch-geometric       1.6.3                     
> torch-scatter            2.0.5                     
> torch-sparse            0.6.8                     
> torch-spline-conv     1.2.0                   
> torchvision               0.7.0                
```
Traceback (most recent call last):
  File "/home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/crypto/anaconda3/envs/graph/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_eval.py", line 8, in <module>
    from src.dataset.data_loader import GMDataset, get_dataloader
  File "/home/crypto/think/src/dataset/data_loader.py", line 9, in <module>
    from src.factorize_graph_matching import kronecker_sparse, kronecker_torch
  File "/home/crypto/think/src/factorize_graph_matching.py", line 4, in <module>
    from src.utils.sparse import bilinear_diag_torch
  File "/home/crypto/think/src/utils/sparse.py", line 8, in <module>
    from src.sparse_torch import CSRMatrix3d, CSCMatrix3d
  File "/home/crypto/think/src/sparse_torch/__init__.py", line 5, in <module>
    from .csx_matrix import CSRMatrix3d, CSCMatrix3d, dot, concatenate
  File "/home/crypto/think/src/sparse_torch/csx_matrix.py", line 15, in <module>
    '/usr/include/python{}.{}/'.format(sys.version_info.major, sys.version_info.minor)]
  File "/home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 974, in load
    keep_intermediates=keep_intermediates)
  File "/home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1179, in _jit_compile
    with_cuda=with_cuda)
  File "/home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1279, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "/home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error building extension 'sparse_dot': ninja: warning: bad deps log signature or version; starting over
[1/4] /usr/local/cuda-10.1/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/include -isystem /home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/include/TH -isystem /home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.1/include -isystem /home/crypto/anaconda3/envs/graph/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/crypto/think/src/extension/sparse_dot/csr_dot_diag_cuda.cu -o csr_dot_diag_cuda.cuda.o 
FAILED: csr_dot_diag_cuda.cuda.o 
/usr/local/cuda-10.1/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/include -isystem /home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/include/TH -isystem /home/crypto/anaconda3/envs/graph/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.1/include -isystem /home/crypto/anaconda3/envs/graph/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/crypto/think/src/extension/sparse_dot/csr_dot_diag_cuda.cu -o csr_dot_diag_cuda.cuda.o 
/home/crypto/think/src/extension/sparse_dot/csr_dot_diag_cuda.cu: In lambda function:
/home/crypto/think/src/extension/sparse_dot/csr_dot_diag_cuda.cu:53:123: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
...
...
/usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
ninja: build stopped: subcommand failed.
```

**Comment by rogerwwww** [comment]
Perhaps you could use our docker image to get rid of these dependency issues?

See: https://github.com/Thinklab-SJTU/ThinkMatch-runtime#get-the-image-by-docker

**Comment by chengzhix** [comment]
yes, I have successfully run the code on docker, thanks for your reply.

**Comment by rogerwwww** [comment]
You are welcome🤗🤗
