### ISSUE TITLE
Can GANN-MGM handle large graph ?

### ISSUE THREAD

**Issue by xiachenrui** [Thinklab-SJTU/ThinkMatch#48]
Hi, your work is really great! I would like to know if the GANN-MGM model can work on very large graphs (with about 30,000 nodes and features  of each node are known).
Do you have any other suggestions about work on large graph?

Thanks  a lot !

**Comment by rogerwwww** [comment]
Hi Chenrui, 

If your graph scales up to 30,000 nodes, perhaps you should first try two-graph matching methods that are more memory efficient. For the GANN-MGM model, the GPU memory might be an issue (or perhaps you could try using CPU and RAM).

I feel like you might be interested in our new pygmtools: https://github.com/Thinklab-SJTU/pygmtools
It provides numpy&pytorch implementations of graph matching methods with a unified python interface.

**Comment by xiachenrui** [comment]
Thanks for reply! I can't wait to try it.
