### ISSUE TITLE
Jupyter, Colab or Kaggle notebooks

### ISSUE THREAD

**Issue by ratthachat** [Thinklab-SJTU/ThinkMatch#49]
Hi thanks for the great library!

I am wondering if there are some examples on Jupyter, Colab or Kaggle notebooks
(esp. to load and apply the pretrain model in a more custom way) ?

**Comment by rogerwwww** [comment]
Hi there,

We do not have Jupyter notebooks (probably because I do not use Jupyter🤣). If anyone has made some interesting Jupyter examples, please start a PR and we will be happy to merge it.
