### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

### ISSUE THREAD

**Issue by Chjx395** [Thinklab-SJTU/ThinkMatch#51]
After I type "python train_eval.py", it raised an error "No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda".
Does anyone meets the same problem?

**Comment by Chjx395** [comment]
> After I type "python train_eval.py", it raised an error "No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda". Does anyone meets the same problem?

It turns out that you should download Nvidia Docker and print "--runtime=nvidia" in the "docker run" sentence to use this docker image. Otherwise the container you open just has no gpu driver.

Forgive my silly question, since this is the 1st time that I use Docker to run a project.  O(∩_∩)O

And thanks the ThinkMatch Team for your kindness and careful introduction of this project.

**Comment by rogerwwww** [comment]
No worries. Glad to see you resolving the problem by yourself😃

**Comment by pronaykp** [comment]
> 

Bro, How can I Dockerize, would you please give the instruction!
Thank you in advanced.

**Comment by rogerwwww** [comment]
@pronaykp Do you have docker installed on your computer? If not, please follow the official guide: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker
