### ISSUE TITLE
Certificates of optimality

### ISSUE THREAD

**Issue by aabbas90** [Thinklab-SJTU/ThinkMatch#53]
Hi,

Thanks for making the code available and elaborate [website](https://thinklab.sjtu.edu.cn/project/NGM/index.html). Regarding NGM I would like to know whether it can provide certificate of optimality i.e. lower bound on the objective value? If not, how can one judge the quality of produced primal solution? 

Thanks,
Ahmed

**Comment by rogerwwww** [comment]
Hi Ahmed,

Thanks for your interest in our project. NGM currently cannot provide a lower bound, in other words, it is a primal method. Perhaps this is a common challenge of existing neural network solvers, and your comments seem to point out an interesting direction for future research.

Best,
Runzhong
