### ISSUE TITLE
Explaning yaml parameters & Pure CPU training

### ISSUE THREAD

**Issue by nlwmode** [Thinklab-SJTU/ThinkMatch#57]
1. 请问有没有针对yaml文件参数的介绍
2. 如果宿主机没有显卡，如何只使用cpu进行训练

---------------------------------

1. Is there any introduction to the parameters of the yaml file?
2. If the host machine does not have a graphics card, how to use only the CPU for training

**Comment by rogerwwww** [comment]
您好，根据您的问题：
1. 特别具体的逐条说明暂时没有，不过doc上有针对每个模型的具体介绍，可供参考 https://thinkmatch.readthedocs.io/en/latest/guide/models.html
2. 可以使用CPU进行训练，把代码里的"device"参数都设成cpu即可。不过可能会非常慢

**Comment by rogerwwww** [comment]
Sorry, I missed this previously. You may see the explanations here: https://github.com/Thinklab-SJTU/ThinkMatch/blob/master/src/utils/config.py

**Comment by rogerwwww** [comment]
I am closing this issue because it is no longer active. Please feel free to re-open it if the issue still exists!
