### ISSUE TITLE
About Synthetic data

### ISSUE THREAD

**Issue by AlexTansley** [Thinklab-SJTU/ThinkMatch#6]
Hey, 

I think you have done an amazing work! Sorry for my stupid question.

How can I get or generate the Synthetic datasets ?

**Comment by rogerwwww** [comment]
Hi Alex, 

We do not include synthetic test code in this release. Now you may follow the experimental part of our paper to generate synthetic data. 

If you guys are really interested, I think we can add them later.

**Comment by rogerwwww** [comment]
I am closing this non-active issue. Feel free to reopen it if you still have any questions.
