### ISSUE TITLE
Can I run on my own dataset?

### ISSUE THREAD

**Issue by Hangiscoming** [Thinklab-SJTU/ThinkMatch#60]
Can I run it on my own data set? If so, do I need to change pygmtools?

------------------------

请问能在自己的数据集上跑吗，如果能需要改pygmtools吗

**Comment by rogerwwww** [comment]
您好，可以在自己的数据集上跑，不需要改pygmtools. 您需要按照pygmtools的接口实现您自己的数据集类，然后就可嵌入现有的框架内。可参考https://pygmtools.readthedocs.io/en/latest/api/_autosummary/pygmtools.dataset.html

**Comment by Hangiscoming** [comment]
> Hello, you can run it on your own data set without changing pygmtools. You need to implement your own data set class according to the interface of pygmtools, and then you can embed it into the existing framework. Please refer to https://pygmtools.readthedocs.io/en/latest/api/_autosummary/pygmtools.dataset.html
> 
> 您好，可以在自己的数据集上跑，不需要改pygmtools. 您需要按照pygmtools的接口实现您自己的数据集类，然后就可嵌入现有的框架内。可参考https://pygmtools.readthedocs.io/en/latest/api/_autosummary/pygmtools.dataset.html

感谢您的回复，还有一个问题，在使用PascalVOC数据集时用到的voc2011_pairs.npz文件是怎么生成的，在自己的数据集上跑时该类似文件是必须要有的吗？

**Comment by rogerwwww** [comment]
不是必须的

**Comment by rogerwwww** [comment]
I am closing this issue because it is no longer active. Please feel free to re-open it if the issue still exists!
