### ISSUE TITLE
question about installing lpmp_py

### ISSUE THREAD

**Issue by jkcc98** [Thinklab-SJTU/ThinkMatch#63]
hello，when i run   python -m pip install git+https://git@github.com/rogerwwww/lpmp.git  in my linux environment，it occurs 
ERROR: Failed building wheel for lpmp-py
  Running setup.py clean for lpmp-py
Failed to build lpmp-py
ERROR: Could not build wheels for lpmp-py, which is required to install pyproject.toml-based projects
i can not handle this error few days 555
do you know why and how to solve it ? thank you very much

**Comment by rogerwwww** [comment]
Hi there, 

It is an error when compiling the LPMP source code. You should find the exact error message thrown by the compiler and then find a way to fix it. As always, it is recommended to use the docker image to avoid such troubles.

**Comment by rogerwwww** [comment]
I am closing this issue because it is no longer active. Please feel free to re-open it if the issue still exists!
