### ISSUE TITLE
How can I visualize the training results of NGM？

### ISSUE THREAD

**Issue by chying1999** [Thinklab-SJTU/ThinkMatch#64]
How can I obtain processed image results like the Visualization section on this website https://thinklab.sjtu.edu.cn/project/NGM/index.html

**Comment by rogerwwww** [comment]
Hi there,

You may take a look at [this example](https://pygmtools.readthedocs.io/en/latest/auto_examples/7.image_matching_by_NN/plot_deep_image_matching_pytorch.html#sphx-glr-auto-examples-7-image-matching-by-nn-plot-deep-image-matching-pytorch-py) and there is visualization code there.

**Comment by chying1999** [comment]
Program error: AttributeError: module 'pygmtools' has no attribute 'set_backend "，and I can not find the set_backend in the pygmtools,my pygmtools version is 0.3.4

**Comment by rogerwwww** [comment]
Please upgrade to the latest version `pip install -U pygmtools`

Or you can replace `pygm.set_backend('pytorch')` by `pygm.backend = 'pytorch'`

**Comment by rogerwwww** [comment]
I am closing this issue because it is no longer active. Please feel free to reopen it if the issue still exists!
