### ISSUE TITLE
ModuleNotFoundError: No module named 'ortools'

### ISSUE THREAD

**Issue by TenshGU** [Thinklab-SJTU/ThinkMatch#67]
It happened package dependency issues when I run the code in the docker image you provided.

```
xx@xxx# python train_eval.py --cfg experiments/vgg16_pca_voc.yaml

Traceback (most recent call last):
  File "train_eval.py", line 11, in <module>
    from src.loss_func import *
  File "/xxx/src/loss_func.py", line 5, in <module>
    from src.lap_solvers.ILP import ILP_solver
  File "/xxx/src/lap_solvers/ILP.py", line 8, in <module>
    from ortools.linear_solver import pywraplp
ModuleNotFoundError: No module named 'ortools'
```

Is this because the package dependency does not exist in the image?

**Comment by TenshGU** [comment]
docker pull runzhongwang/thinkmatch:torch1.6.0-cuda10.1-cudnn7-pyg1.6.3-pygmtools0.3.2

**Comment by TenshGU** [comment]
the docker image pull followed by:

**Comment by rogerwwww** [comment]
Hi there,

Docker images pushed in the past 6 months should have the ``ortools`` package installed. Would you mind trying again with the latest image?

**Comment by TenshGU** [comment]
Yes, I see it has been updated in [ThinkMatch-runtime](https://github.com/Thinklab-SJTU/ThinkMatch-runtime)  
But I pull the image by the following command that show in README.md: 
```  
docker pull runzhongwang/thinkmatch:torch1.6.0-cuda10.1-cudnn7-pyg1.6.3-pygmtools0.3.2  
```  
Maybe the image what I used is the latest one?  
(I am not sure because my current network cannot access dockerhub. I need to go home and check it out on my PC tonight.)

**Comment by rogerwwww** [comment]
Hi, the latest version should be
`docker pull runzhongwang/thinkmatch:torch1.6.0-cuda10.1-cudnn7-pyg1.6.3-pygmtools0.5.1`

Sorry the README is not actively updated.

**Comment by TenshGU** [comment]
the docker image pull followed by:



> Hi, the latest version should be `docker pull runzhongwang/thinkmatch:torch1.6.0-cuda10.1-cudnn7-pyg1.6.3-pygmtools0.5.1`
> 
> Sorry the README is not actively updated.

Thank you so much

**Comment by TenshGU** [comment]
> Hi, the latest version should be `docker pull runzhongwang/thinkmatch:torch1.6.0-cuda10.1-cudnn7-pyg1.6.3-pygmtools0.5.1`
> 
> Sorry the README is not actively updated.

Thank you so much
