### ISSUE TITLE
The parameter `RESCALE` type mismatch when read config from yaml file

### ISSUE THREAD

**Issue by TenshGU** [Thinklab-SJTU/ThinkMatch#68]
Hi, I am so sorry to bother you again.
When I use the following command to run the code:
```
python train_eval.py --cfg experiments/vgg16_pca_willow.yaml
```

A **type mismatch error** raising:
```
Error under config key: PROBLEM
Traceback (most recent call last):
  File "train_eval.py", line 288, in <module>
    args = parse_args('Deep learning of graph matching training & evaluation code.')
  File "/workspace/gm/src/utils/parse_args.py", line 19, in parse_args
    cfg_from_file(f)
  File "/workspace/gm/src/utils/config.py", line 272, in cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/workspace/gm/src/utils/config.py", line 245, in _merge_a_into_b
    _merge_a_into_b(a[k], b[k])
  File "/workspace/gm/src/utils/config.py", line 240, in _merge_a_into_b
    raise ValueError('Type mismatch ({} vs. {}) for config key: {}'.format(type(b[k]), type(v), k))
ValueError: Type mismatch (<class 'tuple'> vs. <class 'list'>) for config key: RESCALE
```

The image I used is:
```
runzhongwang/thinkmatch:torch1.6.0-cuda10.1-cudnn7-pyg1.6.3-pygmtools0.5.1
```
---
Here is my analysis of this error:

- The definition of `PROBLEM.RESCALE` in `src/utils/config.py` as follows:

  ```
  # Rescaled image size
  __C.PROBLEM.RESCALE = (256, 256)
  ```
  which is defined as `tuple` type. 

  The link as follows:
  https://github.com/Thinklab-SJTU/ThinkMatch/blob/f5c832e35a86761ef398fa43e6a4367b05b487f5/src/utils/config.py#L36C1-L37C33

- The definition of `RESCALE` in `vgg16_[model_name]_[dataset_name].yaml` as follows:
  ```
  # Problem configuration
  PROBLEM:
    TYPE: 2GM
    RESCALE:  # rescaled image size
      - 256
      - 256
    FILTER: 'intersection'
  ```
  which means it will be converted to `list` type by the code in the following link:
  https://github.com/Thinklab-SJTU/ThinkMatch/blob/f5c832e35a86761ef398fa43e6a4367b05b487f5/src/utils/config.py#L255C1-L257C44

- when call  `_merge_a_into_b`, recursively merge dicts from `yaml_cfg` to `__C`, the error happened:
  https://github.com/Thinklab-SJTU/ThinkMatch/blob/f5c832e35a86761ef398fa43e6a4367b05b487f5/src/utils/config.py#L235-L240

---
I don't know if it's because there's something wrong with my configuration or what?
Forgive my stupidity.

**Comment by rogerwwww** [comment]
Hi there,

You may modify the type in ``src/utils/config.py`` manually. It seems to be an issue with yaml versions or something else

**Comment by TenshGU** [comment]
> Hi there,
> 
> You may modify the type in `src/utils/config.py` manually. It seems to be an issue with yaml versions or something like that

Thank you so much.
By the way, will there be a follow-up PR to solve this question?

**Comment by rogerwwww** [comment]
I will have to double check what is the real reason of this issue before an official fix. Thanks for reporting!

**Comment by rogerwwww** [comment]
> Add two lines in [config.py](https://github.com/Thinklab-SJTU/ThinkMatch/blob/b3efd1b5710545ed6e8573ba8c9294b4f2da4e21/src/utils/config.py#L258) could make it work. The issue seems to be related to changes in the YAML loading package.
> 
> ```
>    if 'RESCALE' in yaml_cfg['PROBLEM']:
>         yaml_cfg['PROBLEM']['RESCALE'] = tuple(yaml_cfg['PROBLEM']['RESCALE'])
> ```

Thanks! Will update in the master branch
