### ISSUE TITLE
Build Graph Error

### ISSUE THREAD

**Issue by LingXyy** [Thinklab-SJTU/ThinkMatch#71]
elaunay triangulation error detected , Return fully-connected graph,How could I prevent this problem

**Comment by rogerwwww** [comment]
Hi, we are using the Delaunay triangulation algorithm from Scipy: 
```from scipy.spatial import Delaunay```

If you want to avoid this error, please check the error log by directly running the ``Delaunay`` function from Scipy.

**Comment by rogerwwww** [comment]
I am closing this issue because it is no longer active. Please feel free to re-open it if the issue still exists!
