### ISSUE TITLE
Willow-Object-Class Dataset leads to no-where

### ISSUE THREAD

**Issue by yonatansverdlov** [Thinklab-SJTU/ThinkMatch#72]
In the link of the Willow-Object-Class Dataset, the link doesn't lead anywhere.

**Comment by rogerwwww** [comment]
Hi, the Willow-Object-Class webpage is managed by a team at INRIA and is beyond our control. 

You may find an ulternative link of Willow-Object-Class Dataset we maintained:
https://huggingface.co/heatingma/pygmtools/resolve/main/WILLOW-ObjectClass_dataset.zip

**Comment by rogerwwww** [comment]
I am closing this issue because it is no longer active. Please feel free to re-open it if the issue still exists!
