### ISSUE TITLE
Issues when trying to run AFAT-I stage2  

### ISSUE THREAD

**Issue by gtan45** [Thinklab-SJTU/ThinkMatch#75]
Dear authors, 
I tried to run the experiments on AFAT-I model. Running experiments/gcan-afat/vgg16_gcan-afat-i_imcpt_100_stage1.yaml is successful. However, when trying to run /gcan-afat/vgg16_gcan-afat-i_imcpt_100_stage2.yaml, I got the the following error - 

Loading model parameters from output/vgg16_gcan_varied_afat-i_imcpt_100/params/params_0015.pt

FileNotFoundError: [Errno 2] No such file or directory: 'output/vgg16_gcan_varied_afat-i_imcpt_100/params/optim_k_0015.pt'

In the output/vgg16_gcan_varied_afat-i_imcpt_100/params/ directory, I cannot see a optim_k_0015.pt file, but can see optim_0015.pt and params_0015.pt files. Suggestions to fix this issue is greatly appreciated.

**Comment by gtan45** [comment]
This issue still persists. Any help on fixing the issue is greatly appreciated.

**Comment by ziao-guo** [comment]
Sorry for the bug! We have fixed the issue in the latest [commit](https://github.com/Thinklab-SJTU/ThinkMatch/commit/c68c26fbd1912237dafdcfdbb1c66e1ee13ed9ac)!

**Comment by gtan45** [comment]
Thank you very much.
